### ISSUE TITLE
Wireframe Diagram

### ISSUE THREAD

**Issue by bit172** [daphneaugier/kimsquit#5]

**Comment by leojrsilao** [comment]
**Manage courses**
![Manage courses](https://user-images.githubusercontent.com/43038259/69486650-fa08ad80-0e1b-11ea-8300-b24c6483f244.png)
**Announcements**
![Announcement page](https://user-images.githubusercontent.com/43038259/69486648-f9701700-0e1b-11ea-90c0-7900e5f61c9b.png)
**Discussion and questions**
![Discussion and questions](https://user-images.githubusercontent.com/43038259/69486649-fa08ad80-0e1b-11ea-9444-10b629b32ab2.png)
